import { useState } from 'react'
import type { Cliente, Deuda, ItemDeuda, Producto } from '../../domain/types'
import { fmt, todayStr, uid } from '../../lib/formatters'
import { IcoBack, IcoPlus, IcoTrash } from '../../components/icons'
import { Btn, Card, FieldInput, FieldSelect } from '../../components/ui'

type NuevaDeudaProps = { preselectedClienteId?: string | null; clientes: Cliente[]; productos: Producto[]; onSave: (deuda: Deuda) => void; onCancel: () => void }

/** Construye una deuda a partir de un cliente y sus líneas de productos. */
export function NuevaDeuda({ preselectedClienteId, clientes, productos, onSave, onCancel }: NuevaDeudaProps) {
  const [clienteId, setClienteId] = useState(preselectedClienteId ?? '')
  const [fecha, setFecha] = useState(todayStr())
  const [notas, setNotas] = useState('')
  const [items, setItems] = useState<{ productoId: string; cantidad: number }[]>([{ productoId: '', cantidad: 1 }])
  const itemsRich = items.map(item => { const producto = productos.find(value => value.id === item.productoId); return { ...item, producto, subtotal: producto ? producto.precio_unitario * item.cantidad : 0 } })
  const total = itemsRich.reduce((sum, item) => sum + item.subtotal, 0)
  const canSubmit = !!clienteId && !!fecha && items.every(item => !!item.productoId && item.cantidad > 0)
  const handleSubmit = () => { if (!canSubmit) return; const deudaItems: ItemDeuda[] = itemsRich.map(item => ({ producto_id: item.productoId, nombre_producto: item.producto!.nombre, cantidad: item.cantidad, precio_unitario: item.producto!.precio_unitario, subtotal: item.subtotal })); onSave({ id: uid(), cliente_id: clienteId, fecha_fiado: fecha, items: deudaItems, monto_total: total, notas: notas.trim() || undefined, created_at: todayStr() }) }

  return <div className="p-6 max-w-2xl"><div className="flex items-center gap-3 mb-6"><button onClick={onCancel} className="text-[#7d8590] hover:text-[#e6edf3] transition-colors cursor-pointer"><IcoBack /></button><h1 className="text-xl font-semibold text-[#e6edf3]">Nueva deuda (fiado)</h1></div><div className="space-y-5">
    <div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><FieldSelect label="Cliente" value={clienteId} onChange={event => setClienteId(event.target.value)}><option value="">Seleccionar cliente…</option>{clientes.map(cliente => <option key={cliente.id} value={cliente.id}>{cliente.nombre}</option>)}</FieldSelect><FieldInput label="Fecha del fiado" type="date" value={fecha} onChange={event => setFecha(event.target.value)} /></div>
    <div><div className="flex items-center justify-between mb-2"><label className="text-[10px] font-semibold text-[#7d8590] uppercase tracking-widest">Productos</label><Btn variant="ghost" size="sm" onClick={() => setItems(previous => [...previous, { productoId: '', cantidad: 1 }])}><IcoPlus />Agregar línea</Btn></div><Card className="overflow-hidden"><div className="grid grid-cols-[1fr_72px_100px_32px] border-b border-[#30363d] bg-[#161b22]">{['Producto', 'Cant.', 'Subtotal', ''].map(header => <div key={header} className="px-3 py-2 text-[10px] font-semibold text-[#7d8590] uppercase tracking-widest">{header}</div>)}</div>{itemsRich.map((item, index) => <div key={index} className="grid grid-cols-[1fr_72px_100px_32px] border-t border-[#21262d]"><select className="px-3 py-2.5 bg-transparent text-sm text-[#e6edf3] focus:outline-none border-r border-[#21262d]" value={item.productoId} onChange={event => setItems(previous => previous.map((value, itemIndex) => itemIndex === index ? { ...value, productoId: event.target.value } : value))}><option value="">Seleccionar…</option>{productos.map(producto => <option key={producto.id} value={producto.id}>{producto.nombre} — {fmt(producto.precio_unitario)}</option>)}</select><input type="number" min="1" className="px-3 py-2.5 bg-transparent text-sm text-[#e6edf3] font-mono focus:outline-none text-center border-r border-[#21262d]" value={item.cantidad} onChange={event => setItems(previous => previous.map((value, itemIndex) => itemIndex === index ? { ...value, cantidad: Math.max(1, parseInt(event.target.value) || 1) } : value))} /><div className="px-3 flex items-center border-r border-[#21262d]"><span className="text-sm font-mono text-[#e6edf3]">{fmt(item.subtotal)}</span></div><div className="flex items-center justify-center">{items.length > 1 && <button onClick={() => setItems(previous => previous.filter((_, itemIndex) => itemIndex !== index))} className="text-[#484f58] hover:text-[#f85149] cursor-pointer transition-colors p-1"><IcoTrash /></button>}</div></div>)}<div className="flex items-center justify-end gap-3 px-3 py-2.5 border-t border-[#30363d] bg-[#0d1117]"><span className="text-xs text-[#7d8590]">Total a fiar</span><span className="text-base font-mono font-semibold text-[#e6edf3]">{fmt(total)}</span></div></Card></div>
    <FieldInput label="Notas (opcional)" value={notas} onChange={event => setNotas(event.target.value)} placeholder="Observaciones sobre esta venta…" /><div className="flex gap-2 pt-1"><Btn onClick={handleSubmit} disabled={!canSubmit}>Registrar deuda</Btn><Btn variant="ghost" onClick={onCancel}>Cancelar</Btn></div>
  </div></div>
}
